[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[nixpacks]
# Install FFmpeg
installCommand = "apt-get update && apt-get install -y ffmpeg" 